name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  test-on-linux:
    runs-on: ununtu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt --all -- --check --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings --verbose
    - name: Run tests
      run: cargo test --verbose
